- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-27
> MEX-27: Remove checkin component

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-54
> MEX-54 Primary Care

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
Adds address configuration for Mexico, which allows "Other" community field.
> MEX-85: Address should allow "Other" for community, with free text

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-109
> MEX-109: Add BP widget to patient dashboard

- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- manifests/site.pp
- mirebalais-modules/openmrs/files/config/pih-config-mexico-capitan.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-honduras.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-laguna.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-letrero.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-matazano.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-monterrey.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-plan.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-reforma.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-salvador.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-soledad.json
https://tickets.pih-emr.org/browse/MEX-17
> MEX-17: Patient Identifier for CES

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-147
> MEX-147: Should be easy to view patient diabetes clinical history

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-149
Add indigenous, immigrant, and active casefinding to reg
> MEX-149: Add boolean person attributes to Registration: immigrant, indigenous, active casefinding

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
MEX-120 Add yes/no concepts to Registration: Disabled, Can Read
https://tickets.pih-emr.org/browse/MEX-120
> MEX-120 Add yes/no concepts to Registration: Disabled, Can Read

- hieradata/pleebo-mirror.pih-emr.org.yaml
- manifests/site.pp
New file: mirebalais-modules/openmrs/files/config/pih-config-liberia-pleebo.json  for pleebo mirror in upcape server VM. 
Changes in site.pp  @mark @lnball
> New config files for pleebo-mirror

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-73
> MEX-73: Add patient documents support to CES EMR

- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- hieradata/common.yaml
- manifests/site.pp
- mirebalais-modules/tomcat/manifests/init.pp
- mirebalais-modules/tomcat/templates/server.xml.epp
- mirebalais-modules/tomcat/templates/server.xml.erb
https://tickets.pih-emr.org/browse/MEX-204
> MEX-204 Mexico servers should install with the correct tomcat7 settings and apache disabled

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
MEX-207 Enable Mental Health program for CES
https://tickets.pih-emr.org/browse/MEX-207
depends on https://github.com/PIH/openmrs-module-mirebalais/pull/33
> MEX-207 Enable Mental Health program for CES

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
MEX-237 Create minimal Asthma program
https://tickets.pih-emr.org/browse/MEX-237
> MEX-237 Create minimal Asthma program

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
MEX-236 Create minimal Epilepsy program
https://tickets.pih-emr.org/browse/MEX-236
> MEX-236 Create minimal Epilepsy program

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
MEX-208 Create/Enable Maternal Health program for CES
https://tickets.pih-emr.org/browse/MEX-208
> MEX-208 Create/Enable Maternal Health program for CES

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-247
Removes the visitNote component from CES
> MEX-247 Switch back to old Visit format

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://tickets.pih-emr.org/browse/MEX-242
> MEX-242 Create minimal Malnutrition program

- README.md
- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- hieradata/ces.pih-emr.org.yaml
- mirebalais-modules/openmrs/files/app-data-config/mexico/configuration/addresshierarchy/addressConfiguration.xml
- mirebalais-modules/openmrs/files/app-data-config/mexico/configuration/addresshierarchy/mexico_address_hierarchy_entries.csv
- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
- mirebalais-modules/openmrs/manifests/init.pp
https://tickets.pih-emr.org/browse/MEX-235
Puts the Mexico AH configuration in config files. Adds Puppet support for creating a configuration directory in the app data directory based on a new hieradata parameter.
> MEX-86 Address should have INEGI fields - EDO, MUN, LOC

- hieradata/jjdossen.pih-emr.org.yaml
- manifests/site.pp
- mirebalais-modules/openmrs/files/config/pih-config-liberia-harper-jjdossen.json
- mirebalais-modules/openmrs/files/config/pih-config-liberia-jjdossen.json
- Added JJ Dossen as site/facility supported
- Added config files
> LIB: Added JJ Dossen as site/facility supported, added config files

- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
https://tickets.pih-emr.org/browse/MEX-203
> MEX-203: Change Mexico server timezones to Mexico City

- mirebalais-modules/openmrs/files/config/pih-config-sierraLeone.json
Adding vitals to Sierra Leone config file
> SL add vitals component

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://pihemr.atlassian.net/browse/MEX-314
> MEX-314 Switch CES from using MCH Program to ANC Program

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://pihemr.atlassian.net/browse/MEX-19
> MEX-19  Print Patient Consult Note Summaries

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://pihemr.atlassian.net/browse/MEX-362
> MEX-362 Height/weight graph on main patient dashboard

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://pihemr.atlassian.net/browse/MEX-364
> MEX-364 Manual address entry fields don't accept user input

- mirebalais-modules/openmrs/files/config/pih-config-sierraLeone-gladi.json
- mirebalais-modules/openmrs/files/config/pih-config-sierraLeone-wellbody.json
Origin previously set to lebbieSahr repository now pointing to PIH - change caused these files to be modified
> files modified as origin previously incorrectly configured

- hieradata/ces-demo.pih-emr.org.yaml
- mirebalais-modules/openmrs/files/config/pih-config-mexico-capitan.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-demo.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-honduras.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-laguna.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-letrero.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-matazano.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-monterrey.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-plan.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-production.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-reforma.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-salvador.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico-soledad.json
https://pihemr.atlassian.net/browse/MEX-399
Will need a change to `site.pp`. Can I leave that to you, @jmbabazi ?
> MEX-399 Set up production CES cloud server

- mirebalais-modules/mirebalais_reporting/manifests/production_setup.pp
- mirebalais-modules/mirebalais_reporting/manifests/reporting_setup.pp
@mogoodrich, just changed the hours. Let me know if you think there might be other conflicts
> Changing cron hrs to accommodate petl execution time

- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
Pulling in last-minute changes for launch.
At some point it would be great to learn how to publish things to the stable branch.
> Set all CES sites to the unstable branch

- mirebalais-modules/openmrs/files/app-data-config/mexico/configuration/addresshierarchy/mexico_address_hierarchy_entries.csv
https://pihemr.atlassian.net/browse/MEX-425
> MEX-425 Strange address hierarchy behavior when not all levels present

- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
This reverts commit faa88faf7f11318a4b9cc611943b9315e8d592f2.
> Revert "Set all CES sites to the unstable branch"

- mirebalais-modules/openmrs/files/config/pih-config-sierraLeone-gladi.json
> added in mch component

- manifests/site.pp
- mirebalais-modules/cesemr_user_resources/manifests/init.pp
https://pihemr.atlassian.net/browse/MEX-429
> MEX-429 Add documentation to puppet install

- mirebalais-modules/openmrs/files/config/pih-config-haiti.json
- mirebalais-modules/openmrs/files/config/pih-config-mirebalais.json
@mogoodrich @lnball  @cioan 
Would you like to review this modification for me please
> UHM-4096 Add MH CHW Supervisor provider

- hieradata/ces-ci.pih-emr.org.yaml
- hieradata/common.yaml
- mirebalais-modules/openmrs/manifests/init.pp
https://pihemr.atlassian.net/browse/MEX-129
> MEX-129 Make session timeout longer

- mirebalais-modules/openmrs/files/config/pih-config-sierraLeone-gladi.json
Programmes not being used at present so removing from dashboards.  @lnball / @mogoodrich for your review.
> remove program section

- mirebalais-modules/openmrs/files/config/pih-config-sierraLeone-gladi.json
Adds relationships.
@mogoodrich / @lnball please review
> added relationships

- hieradata/ces-capitan.yaml
- hieradata/ces-demo.pih-emr.org.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- hieradata/ces.pih-emr.org.yaml
https://pihemr.atlassian.net/browse/MEX-129
> Add timeout parameter to all CES deployments

- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
https://pihemr.atlassian.net/browse/MEX-65
> MEX 65: Make registration lead to clinical dashboard

- hieradata/peru-ci.pih-emr.org.yaml
- manifests/site.pp
- mirebalais-modules/openmrs/files/app-data-config/peru/configuration/addresshierarchy/addressConfiguration.xml
- mirebalais-modules/openmrs/files/app-data-config/peru/configuration/addresshierarchy/peru_address_hierarchy_entries.csv
- mirebalais-modules/openmrs/files/app-data-config/peru/configuration/globalproperties/gp.xml
- mirebalais-modules/openmrs/files/app-data-config/peru/configuration/locations/locations.csv
- mirebalais-modules/openmrs/files/config/pih-config-liberia.json
- mirebalais-modules/openmrs/files/config/pih-config-mexico.json
- mirebalais-modules/openmrs/files/config/pih-config-peru.json
https://pihemr.atlassian.net/browse/PER-334
Depends on https://github.com/PIH/openmrs-module-pihcore/pull/137
> PER-334: Set up site for Peru

- mirebalais-modules/openmrs/files/app-data-config/mexico/configuration/globalproperties/gp.xml
To get rid of most of https://github.com/PIH/openmrs-module-pihcore/blob/master/api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataBundle.java
> Add iniz gp file for Mexico

- mirebalais-modules/openmrs/files/app-data-config/mexico/configuration/globalproperties/gp.xml
The last thing to be accounted for of the GPs in https://github.com/PIH/openmrs-module-pihcore/blob/master/api/src/main/java/org/openmrs/module/pihcore/deploy/bundle/mexico/MexicoMetadataBundle.java
> Add Mexico diagnosis set of sets GP to gp.xml

- mirebalais-modules/openmrs/files/app-data-config/peru/configuration/globalproperties/gp.xml
Get rid of the extremely verbose method trace logs
> Add logging setting to peru

- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- hieradata/ces.pih-emr.org.yaml
https://pihemr.atlassian.net/browse/MEX-486
> MEX-486: Update all CES sites to Release 93; return to stable

- hieradata/jjdossen.pih-emr.org.yaml
- hieradata/kouka.pih-emr.org.yaml
- hieradata/pleebo.pih-emr.org.yaml
- LIB - Updating config version for jjdossen and pleebo to 1.1.1 and for kouka to 1.1.2-SNAPSHOT
- Updating database backup configs (server, dir and user)
>  Updating config version for jjdossen and pleebo to 1.1.1 and for kouka to 1.1.2-SNAPSHOT

- hieradata/ces-ci.pih-emr.org.yaml
- hieradata/ci.pih-emr.org.yaml
- hieradata/common.yaml
- mirebalais-modules/openmrs/files/import-map.ci.json
- mirebalais-modules/openmrs/manifests/init.pp
- mirebalais-modules/openmrs/manifests/spa.pp
Packages are built by Bamboo in the [MFE project](https://bamboo.pih-emr.org/browse/MFE).
> Add puppet parameters for SPA and SPA CI

- mirebalais-modules/openmrs/files/import-map.ci.json
> Fix referrals queue in import-map.ci.json

- hieradata/ces-ci.pih-emr.org.yaml
- hieradata/ci.pih-emr.org.yaml
- hieradata/common.yaml
- hieradata/humci.pih-emr.org.yaml
- mirebalais-modules/openmrs/manifests/spa.pp
https://pihemr.atlassian.net/browse/UHM-4490
See https://github.com/PIH/spa-frontend/pull/2
> UHM-4490: Create versioning/release system for spa-frontend packages

- hieradata/emr.hum.ht.yaml
- hieradata/emrtest.hum.ht.yaml
- hieradata/humdemo.pih-emr.org.yaml
- hieradata/reporting.hum.ht.yaml
- hieradata/zltraining.pih-emr.org.yaml
See https://github.com/PIH/spa-frontend/pull/6
> Use mirebalais-latest SPA packages for sites with /mirebalais base URL

- hieradata/ces-capitan.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-monterrey.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- hieradata/ces.pih-emr.org.yaml
https://pihemr.atlassian.net/browse/UHM-4576
> Update all CES servers to Release 96

- hieradata/ces-capitan.yaml
- hieradata/ces-laguna.yaml
- manifests/site.pp
Create ces-laguna.pih-emr.org and ces-capitan.pih-emr.org configuration
> Add configurations for CES pilot servers 

- hieradata/ces-capitan.yaml
- hieradata/ces-laguna.yaml
The cloud EMRs should have their own files like ces-capitan.pih-emr.org.yaml
> Change ces-capitan and ces-laguna back to configuring the laptop-servers.

- mirebalais-modules/openmrs/templates/backupAzure.sh.erb
- mirebalais-modules/openmrs/templates/mysqlarchive.sh.erb
@mogoodrich , I made some improvements to the archive and azcopy scripts. Would you please review.
> Improvement to scripts

- hieradata/pleebo.pih-emr.org.yaml
> config version for pleebo

- hieradata/ces-capitan.yaml
- hieradata/ces-ci.pih-emr.org.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.pih-emr.org.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- hieradata/ces.pih-emr.org.yaml
update report CES medications
update logo Consult Paper Records
> release ces 1.6.0

- mirebalais-modules/openmrs/manifests/init.pp
> Temporarily disable SPA webapp name change step

- hieradata/ami-azure.pih-emr.org.yaml
- hieradata/ami.pih-emr.org.yaml
- hieradata/belladere.pih-emr.org.yaml
- hieradata/boucancarre.pih-emr.org.yaml
- hieradata/ci.pih-emr.org.yaml
- hieradata/emr.hum.ht.yaml
- hieradata/emrtest.hum.ht.yaml
- hieradata/haiti-test.pih-emr.org.yaml
- hieradata/haitihivtest.pih-emr.org.yaml
- hieradata/haititest.pih-emr.org.yaml
- hieradata/hsn.pih-emr.org.yaml
- hieradata/humci.pih-emr.org.yaml
- hieradata/humdemo.pih-emr.org.yaml
- hieradata/humtest.pih-emr.org.yaml
- hieradata/lacolline.pih-emr.org.yaml
- hieradata/reporting.hum.ht.yaml
- hieradata/thomonde.pih-emr.org.yaml
- hieradata/vagrant-test.pih-emr.org.yaml
Can you confirm this is correct for ZL?
> UHM-5643 Release of ZL 1.25.0-SNAPSHOT and 1.24.0

- hieradata/ami.pih-emr.org.yaml
- hieradata/emr.hum.ht.yaml
- hieradata/haitihivtest.pih-emr.org.yaml
- hieradata/haititest.pih-emr.org.yaml
- hieradata/hinche-ci.pih-emr.org.yaml
- hieradata/hinche.pih-emr.org.yaml
- hieradata/hsn.pih-emr.org.yaml
- hieradata/humci.pih-emr.org.yaml
- hieradata/humdemo.pih-emr.org.yaml
- hieradata/lacolline.pih-emr.org.yaml
- hieradata/thomonde.pih-emr.org.yaml
- hieradata/zlemr.pih-emr.org.yaml
- hieradata/zltraining.pih-emr.org.yaml
See https://s01.oss.sonatype.org/content/repositories/snapshots/org/pih/openmrs/openmrs-frontend-zl/
and https://s01.oss.sonatype.org/content/repositories/releases/org/pih/openmrs/openmrs-frontend-zl/
https://pihemr.atlassian.net/browse/UHM-6171
> UHM-6171: Move ZL servers to frontend-zl package

- hieradata/ces-capitan.yaml
- hieradata/ces-ci.pih-emr.org.yaml
- hieradata/ces-honduras.yaml
- hieradata/ces-laguna.pih-emr.org.yaml
- hieradata/ces-letrero.yaml
- hieradata/ces-matazano.yaml
- hieradata/ces-plan.yaml
- hieradata/ces-reforma.yaml
- hieradata/ces-salvador.yaml
- hieradata/ces-soledad.yaml
- hieradata/ces.pih-emr.org.yaml
Ya cheque los cambios en CES-CI
> release CES 1.19.0

- gem-update.sh
- hiera.yaml
Pretty sure we no longer use this, so just wanted to clean up before we forgot... thoughts @jmbabazi ?
> remove references to environment var that is no longer used
